create table "public"."test4migrate" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "testname" text
);


CREATE UNIQUE INDEX test4migrate_pkey ON public.test4migrate USING btree (id);

alter table "public"."test4migrate" add constraint "test4migrate_pkey" PRIMARY KEY using index "test4migrate_pkey";


